import Main from '../component/Main'
import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../component/Sidebar'
import style from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Chart Dashboard </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/chart.jpeg" />
      </Head>
     <div className={style.header}>
     <Sidebar/>
     <Main/>
  </div> 
    </>
  )
}
